project:
  type: website
website:
  title: "MA388 Sabermetrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lessons 1-10
        menu:
          - href: lessons/lsn_1_course_intro.qmd
            text: "Lesson 1: Course Introduction"
          - href: lessons/lsn_2_intro_to_R.qmd 
            text: "Lesson 2: Introduction to R"
          - href: lessons/lsn_3_intro_to_R_II.qmd
            text: "Lesson 3: Introduction to R II"
          - href: lessons/lsn_4_r_graphics_I.qmd
            text: "Lesson 4: R Graphics I"
          - href: lessons/lsn_5_r_graphics_II.qmd
            text: "Lesson 5: R Graphics II"          
          - href: lessons/lsn_6_runs_and_wins_I.qmd
            text: "Lesson 6: Runs and Wins I"
          - href: lessons/lsn_8_runs_and_wins_II.qmd
            text: "Lesson 8: Runs and Wins II"
          - href: lessons/lsn_9_runs_expectancy_matrix.qmd
            text: "Lesson 9: Value of Plays: Run Expectancy Matrix"
          - href: lessons/lsn_10_hits_stealing.qmd
            text: "Lesson 10: Value of Plays: Base Hits and Stealing"
      - text: Lessons 11-20
        menu:
          - href: lessons/lsn_11_swinging_tendencies.qmd
            text: "Lesson 11: Behaviors by Count: Swinging Tendencies"
          - href: lessons/lsn_12_umpire_tendencies.qmd
            text: "Lesson 12: Behaviors by Count: Umpire Tendencies"
          - href: lessons/lsn_13_catcher_framing_visualization.qmd
            text: "Lesson 13: Catcher Framing Ability - Visualizations"
          - href: lessons/lsn_14_logistic_regression.qmd
            text: "Lesson 14: Introduction to Logistic Regression"
          - href: lessons/lsn_15_catcher_framing_modeling.qmd
            text: "Lesson 15: Catcher Framing Ability: Modeling"
          - href: lessons/lsn_16_catcher_framing_random_effects.qmd
            text: "Lesson 16: Catcher Framing Ability: Random Effects"
          - href: lessons/lsn_18_peak_trajectories_I.qmd
            text: "Lesson 18: Comparing Peak Trajectories I"
          - href: lessons/lsn_19_peak_trajectories_II.qmd
            text: "Lesson 19: Comparing Peak Trajectories II"
          - href: lessons/lsn_20_multilevel_modeling.qmd
            text: "Lesson 20: Multilevel Modeling"
      - text: Lessons 21-30
        menu:
          - href: lessons/lsn_21_simulation_I.qmd
            text: "Lesson 21: Simulating Baseball - Part I"
          - href: lessons/lsn_22_simulation_II.qmd
            text: "Lesson 22: Simulating Baseball - Part II"
          - href: lessons/lsn_23_the_great_streak.qmd
            text: "Lesson 23: Baseball Streaks - The Great Streak"
          - href: lessons/lsn_24_streakiness_statistics.qmd
            text: "Lesson 24: Baseball Streaks - Streakiness Statistics"
          - href: lessons/lsn_26_statcast_spray_charts.qmd
            text: "Lesson 26: Working with Large Data - Statcast Spray Charts"
          - href: lessons/lsn_27_launch_angles_exit_velocity.qmd
            text: "Lesson 27: Working with Large Data - Launch Angles and Exit Velocity" 
          - href: lessons/lsn_28_home_run_hitting_I.qmd
            text: "Lesson 28: Home Run Hitting I" 
          - href: lessons/lsn_29_home_run_hitting_II.qmd
            text: "Lesson 29: Home Run Hitting II"     
          - href: lessons/lsn_30_equivalence_coefficient.qmd
            text: "Lesson 30: Equivalence Coefficient" 
      - text: Lessons 31-40
        menu:
          - href: lessons/lsn_31_ops+_babip.qmd
            text: "Lesson 31: OPS+ and BABIP"
          - href: lessons/lsn_32_linear_weights.qmd
            text: "Lesson 32: Linear Weights"
          - href: lessons/lsn_33_runs_created_solution.qmd
            text: "Lesson 33: Runs Created School"
          - href: lessons/lsn_34_quarto_presentations.qmd
            text: "Lesson 34: Quarto Presentations"
          - href: lessons/lsn_34_quarto_presentation_demo.qmd
            text: "Example Quarto Presentation"
          - href: lessons/lsn_35_shiny.qmd
            text: "Lesson 35: Shiny"  
      - href: calendar/calendar.qmd
        text: Calendar
      - href: grab_bag/grab_bag.qmd
        text: 'Grab Bag Topics'
      - href: grab_bag/march_madness.qmd
        text: 'March Madness'
format:
  html:
    theme: cosmo
    toc: true

    
execute:
  freeze: auto   # Ensures code is executed during render
